version: '3.9'

# Source: https://www.youtube.com/watch?v=5N6gTVCG_rw
# alias artisan="docker-compose exec php php /var/www/html/artisan"
# Run: docker-compose run nodejs npm --version to verify if node and npm works

networks:
  laravel:

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfilenodejs
    container_name: nodejs
    volumes:
      - ./src:/home/node/app
      - ./src/node_modules:/home/node/app/node_modules
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.35
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

